# Generated by Django 4.2.1 on 2023-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kurulus_adi', models.TextField()),
                ('Kurulus_logo', models.TextField()),
                ('Kurulus_turu', models.TextField()),
                ('Ulke', models.TextField()),
                ('Firma_website', models.TextField()),
                ('Calisan_sayisi', models.TextField()),
            ],
        ),
    ]
