# Generated by Django 4.2.1 on 2023-06-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='Calisan_sayisi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Firma_website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Kurulus_adi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Kurulus_logo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Kurulus_turu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Ulke',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
