# Generated by Django 4.2.1 on 2023-06-04 13:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companies_calisan_sayisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='Ulke',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
