# Generated by Django 4.2.1 on 2023-06-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_ulke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='Kurulus_turu',
        ),
    ]
