# Generated by Django 4.2.1 on 2023-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_companies_kurulus_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='Kurulus_turu',
            field=models.CharField(choices=[('Şahıs', 'Şahıs'), ('Büyük işletme', 'Büyük işletme'), ('KOBİ', 'KOBİ'), ('STK', 'STK')], max_length=200, null=True),
        ),
    ]
