# Generated by Django 4.2.1 on 2023-06-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companies_kurulus_turu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='Calisan_sayisi',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Firma_website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='Kurulus_logo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
