# Generated by Django 4.2.1 on 2023-06-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_companies_calisan_sayisi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
